# Generated by Django 2.0.5 on 2020-05-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deptno', models.CharField(max_length=50)),
                ('dname', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'department',
            },
        ),
    ]
