# Generated by Django 2.0.5 on 2020-05-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_manage', '0004_leave_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave_form',
            old_name='Doctor_no',
            new_name='doctor_no',
        ),
        migrations.AddField(
            model_name='leave_form',
            name='available',
            field=models.CharField(default='Not available', max_length=20),
        ),
    ]
