# Generated by Django 2.0.5 on 2020-05-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_manage', '0005_auto_20200520_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_form',
            name='available',
            field=models.CharField(choices=[('available', 'available'), ('not available', 'not available')], default='Not available', max_length=20),
        ),
    ]
