# Generated by Django 2.0.5 on 2020-05-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_manage', '0006_auto_20200520_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('department', models.CharField(max_length=50)),
                ('doctor', models.CharField(max_length=50)),
                ('appointment_date', models.DateField()),
                ('gender', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'appointment',
            },
        ),
    ]
