# Generated by Django 2.0.5 on 2020-05-28 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_manage', '0008_auto_20200527_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_form',
            name='available',
            field=models.CharField(default='', max_length=20),
        ),
    ]
