# Generated by Django 2.0.5 on 2020-05-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_manage', '0009_auto_20200528_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave_form',
            name='available',
            field=models.CharField(choices=[('available', 'available'), ('not available', 'not available')], default='Not Available', max_length=20),
        ),
    ]
