# Generated by Django 2.0.5 on 2020-05-29 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_manage', '0010_auto_20200528_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave_form',
            old_name='available',
            new_name='status',
        ),
    ]
