# Generated by Django 2.0.5 on 2020-06-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_manage', '0011_auto_20200529_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.AlterField(
            model_name='leave_form',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('Not available', 'Not available')], default='Not Available', max_length=20),
        ),
    ]
