# Generated by Django 2.0.5 on 2020-06-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_manage', '0012_auto_20200601_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default='', upload_to='pics'),
        ),
    ]
